#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
import shutil
import sys
import time
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

VERSION = "0.1.4"
MARKER = "[SMML-GP0-LAB]"

TARGETS = {
    "Survival/Scripts/game/SurvivalGame.lua": "934beb15dff2f34638128a56aa1be8586e363bc1a5d564698e9b8f09bf9d35c4",
    "Survival/Scripts/game/SurvivalPlayer.lua": "960d15b4a5f66e1fd9ea4af6bd81a6088893b9f71bd8c1ad9c6bafaa592ecf76",
    "Survival/Scripts/game/tools/CarryTool.lua": "ddbb727a8fb687f290f35ff359d626bdcf4983930c51ad24daadd26ee8702dbf",
    "Survival/Scripts/game/interactables/ResourceContainer.lua": "ccd77da5aaa6b6a8e640dc115e123a7236f0df40e31b56277d01314371cdc042",
}

CACHE_PATH = "Cache/Bundle/core_data.cbo"
CACHE_SHA256 = "682efa4378e69f1a711e1d2147c302fbdd0dc8035f841c948d50c50964181351"
PROBE_DIR = "Survival/Scripts/SMMLProbe"
RUNTIME_FILES = {
    f"{PROBE_DIR}/Runtime.lua": "payload/Runtime.lua",
    f"{PROBE_DIR}/Lab.lua": "payload/Lab.lua",
    f"{PROBE_DIR}/LabData.lua": "payload/LabData.lua",
}
CONFIG_PATH = f"{PROBE_DIR}/LabConfig.lua"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp-{os.getpid()}")
    with tmp.open("wb") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def default_state_dir() -> Path:
    override = os.environ.get("SMML_GP0_LAB_STATE")
    if override:
        return Path(override).expanduser()
    base = os.environ.get("XDG_STATE_HOME")
    if base:
        return Path(base) / "smml" / "gp0-carry-storage-lab"
    return Path.home() / ".local" / "state" / "smml" / "gp0-carry-storage-lab"


def game_running() -> list[str]:
    hits: list[str] = []
    proc = Path("/proc")
    if not proc.is_dir():
        return hits
    for child in proc.iterdir():
        if not child.name.isdigit():
            continue
        try:
            cmd = (child / "cmdline").read_bytes().replace(b"\0", b" ").decode("utf-8", "ignore")
            comm = (child / "comm").read_text("utf-8", errors="ignore").strip()
        except OSError:
            continue
        hay = (comm + " " + cmd).lower()
        if "scrapmechanic.exe" in hay or "scrap mechanic/release/scrapmechanic" in hay:
            hits.append(f"pid={child.name} {comm} {cmd[:180]}")
    return hits


def require_game_stopped() -> None:
    hits = game_running()
    if hits:
        raise SystemExit("Scrap Mechanic appears to be running:\n" + "\n".join(hits))


def state_path(state_dir: Path) -> Path:
    return state_dir / "state.json"


def load_state(state_dir: Path) -> dict:
    path = state_path(state_dir)
    if not path.is_file():
        raise SystemExit(f"Lab state not found: {path}")
    return json.loads(path.read_text("utf-8"))


def save_state(state_dir: Path, state: dict) -> None:
    state_dir.mkdir(parents=True, exist_ok=True)
    atomic_write(state_path(state_dir), (json.dumps(state, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def lua_bool(value: bool) -> str:
    return "true" if value else "false"


def render_config(enabled: bool, run_id: str, manual_loadout: bool = True) -> bytes:
    text = f'''-- Generated by smml_gp0_lab.py v{VERSION}.\n__SMML_GP0_LAB_CONFIG = {{\n    enabled = {lua_bool(enabled)},\n    runId = "{run_id}",\n    manualLoadout = {lua_bool(manual_loadout)}\n}}\nreturn __SMML_GP0_LAB_CONFIG\n'''
    return text.encode("utf-8")


def ensure_prefix(file_name: str) -> str:
    return f'''-- SMML_GP0_LAB_BEGIN:bootstrap:{file_name}\nlocal function __smml_gp0_ensureRuntime( source )\n    if type( __SMML_GP0_PROBE ) ~= "table" or __SMML_GP0_PROBE.version ~= "{VERSION}" then\n        if type( pcall ) == "function" then\n            local ok, err = pcall( dofile, "$SURVIVAL_DATA/Scripts/SMMLProbe/Runtime.lua" )\n            if not ok and type( sm ) == "table" and type( sm.log ) == "table" and type( sm.log.error ) == "function" then\n                sm.log.error( "[SMML-GP0-LAB] FALLBACK|event=runtime.load.error|source=" .. tostring( source ) .. "|detail=" .. tostring( err ) )\n            end\n        end\n    end\n    if type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.bootstrap ) == "function" then\n        __SMML_GP0_PROBE.bootstrap( source )\n        return true\n    end\n    return false\nend\n__smml_gp0_ensureRuntime( "{file_name}.file" )\n-- SMML_GP0_LAB_END:bootstrap:{file_name}\n'''


def inject_after_once(text: str, anchor: str, insertion: str, label: str) -> str:
    count = text.count(anchor)
    if count != 1:
        raise RuntimeError(f"{label}: expected one anchor, found {count}: {anchor!r}")
    return text.replace(anchor, anchor + insertion, 1)


def inject_before_once(text: str, anchor: str, insertion: str, label: str) -> str:
    count = text.count(anchor)
    if count != 1:
        raise RuntimeError(f"{label}: expected one anchor, found {count}: {anchor!r}")
    return text.replace(anchor, insertion + anchor, 1)


def apply_patch(rel: str, original: bytes) -> bytes:
    use_crlf = b"\r\n" in original and original.count(b"\r\n") == original.count(b"\n")
    text = original.decode("utf-8")
    if use_crlf:
        text = text.replace("\r\n", "\n")
    name = Path(rel).name
    text = ensure_prefix(name) + text

    if rel == "Survival/Scripts/game/SurvivalGame.lua":
        text = inject_after_once(
            text,
            "function SurvivalGame.server_onCreate( self )\n",
            '''\t-- SMML_GP0_LAB_BEGIN:SurvivalGame.server_onCreate\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.lab ) == "table" and type( __SMML_GP0_PROBE.lab.onGameCreate ) == "function" then\n\t\t__SMML_GP0_PROBE.lab.onGameCreate( self )\n\tend\n\t-- SMML_GP0_LAB_END:SurvivalGame.server_onCreate\n''',
            rel,
        )
        text = inject_after_once(
            text,
            "function SurvivalGame.server_onFixedUpdate( self, timeStep )\n",
            '''\t-- SMML_GP0_LAB_BEGIN:SurvivalGame.server_onFixedUpdate\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.lab ) == "table" and type( __SMML_GP0_PROBE.lab.tick ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_PROBE.lab.tick, self, timeStep )\n\t\tif not ok and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t__SMML_GP0_PROBE.mark( "lab.tick.error", { detail = err } )\n\t\tend\n\tend\n\t-- SMML_GP0_LAB_END:SurvivalGame.server_onFixedUpdate\n''',
            rel,
        )
        text = inject_after_once(
            text,
            "function SurvivalGame.server_onPlayerJoined( self, player, newPlayer )\n",
            '''\t-- SMML_GP0_LAB_BEGIN:SurvivalGame.server_onPlayerJoined\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.lab ) == "table" and type( __SMML_GP0_PROBE.lab.onPlayerJoined ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_PROBE.lab.onPlayerJoined, self, player, newPlayer )\n\t\tif not ok and type( __SMML_GP0_PROBE.mark ) == "function" then __SMML_GP0_PROBE.mark( "lab.player.error", { detail = err } ) end\n\tend\n\t-- SMML_GP0_LAB_END:SurvivalGame.server_onPlayerJoined\n''',
            rel,
        )
        text += '''\n-- SMML_GP0_LAB_BEGIN:SurvivalGame.clientMessage\nfunction SurvivalGame.cl_smmlGp0LabMessage( self, params )\n\tif params and params.text and type( sm ) == "table" and type( sm.gui ) == "table" and type( sm.gui.chatMessage ) == "function" then\n\t\tsm.gui.chatMessage( "[SMML GP0] " .. tostring( params.text ) )\n\tend\nend\n-- SMML_GP0_LAB_END:SurvivalGame.clientMessage\n'''

    elif rel == "Survival/Scripts/game/SurvivalPlayer.lua":
        # Bootstrap-only hook. This file is intentionally used as an early entry point.
        pass

    elif rel == "Survival/Scripts/game/tools/CarryTool.lua":
        start = '''\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.begin\n\tlocal __smml_gp0_insertStart = primaryState == sm.tool.interactState.start\n\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t__SMML_GP0_PROBE.mark( "carry.tryInsert.begin", { side = "client", carryUuid = carryUuid, primaryState = primaryState } )\n\tend\n\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.begin\n'''
        text = inject_after_once(text, "function CarryTool.cl_tryInsert( self, character, primaryState, playerCarry, carryUuid, playerCarryColor )\n", start, rel)

        ray = '''\n\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.raycast\n\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t__SMML_GP0_PROBE.mark( "carry.raycast", { success = success, resultType = result and result.type or "nil" } )\n\tend\n\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.raycast\n'''
        text = inject_after_once(text, "\tlocal success, result = sm.localPlayer.getRaycast( aimRange )\n", ray, rel)

        body_target = '''\n\t\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.bodyTarget\n\t\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t__SMML_GP0_PROBE.mark( "carry.target", { branchCandidate = "body", targetUuid = shapeUuid } )\n\t\tend\n\t\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.bodyTarget\n'''
        text = inject_after_once(text, "\t\tlocal shapeUuid = shape:getShapeUuid()\n", body_target, rel)

        container_check = '''\n\t\t\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.containerCheck\n\t\t\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t\tlocal __smml_accepts = isAnyOf( carryUuid, containerTarget.accepts )\n\t\t\t\tlocal __smml_canCollect = shapeContainer ~= nil and sm.container.canCollect( shapeContainer, carryUuid, 1 )\n\t\t\t\t__SMML_GP0_PROBE.mark( "carry.branch", { branch = "container", targetUuid = shapeUuid, carryUuid = carryUuid, accepts = __smml_accepts, canCollect = __smml_canCollect, containerSlot = containerTarget.slot } )\n\t\t\tend\n\t\t\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.containerCheck\n'''
        text = inject_after_once(text, "\t\t\tlocal shapeContainer = shape.interactable:getContainer( containerTarget.slot )\n", container_check, rel)

        generic_check = '''\n\t\t\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.genericCheck\n\t\t\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t\t__SMML_GP0_PROBE.mark( "carry.branch", { branch = "generic", targetUuid = shapeUuid, carryUuid = carryUuid, accepts = isAnyOf( carryUuid, genericAccepts ) } )\n\t\t\tend\n\t\t\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.genericCheck\n'''
        text = inject_after_once(text, "\t\tif genericAccepts then\n", generic_check, rel)

        harvest_check = '''\n\t\t-- SMML_GP0_LAB_BEGIN:CarryTool.cl_tryInsert.harvestableCheck\n\t\tif __smml_gp0_insertStart and type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t__SMML_GP0_PROBE.mark( "carry.branch", { branch = "harvestable", targetUuid = harvestable.uuid, carryUuid = carryUuid, requiredCarry = requiredCarry, accepts = requiredCarry ~= nil and carryUuid == requiredCarry } )\n\t\tend\n\t\t-- SMML_GP0_LAB_END:CarryTool.cl_tryInsert.harvestableCheck\n'''
        text = inject_after_once(text, "\t\tlocal requiredCarry = HarvestableInsertTargets[tostring(harvestable.uuid)]\n", harvest_check, rel)

        rpc_line = '\t\t\t\t\tself.network:sendToServer( "sv_n_sendItem", params )\n'
        if text.count(rpc_line) != 2:
            raise RuntimeError(f"{rel}: expected two sv_n_sendItem client RPC lines, found {text.count(rpc_line)}")
        rpc_instrumented = '''\t\t\t\t\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t\t\t\t__SMML_GP0_PROBE.mark( "carry.rpc.client", { rpc = "sv_n_sendItem", targetUuid = shapeUuid, carryUuid = carryUuid } )\n\t\t\t\t\tend\n''' + rpc_line
        text = text.replace(rpc_line, rpc_instrumented, 2)

        harvest_rpc_line = '\t\t\t\tself.network:sendToServer( "sv_n_sendItemToHarvestable", params )\n'
        text = inject_before_once(
            text,
            harvest_rpc_line,
            '''\t\t\t\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t\t\t\t__SMML_GP0_PROBE.mark( "carry.rpc.client", { rpc = "sv_n_sendItemToHarvestable", targetUuid = harvestable.uuid, carryUuid = carryUuid } )\n\t\t\t\tend\n''',
            rel,
        )

        server_rpc = '''\t-- SMML_GP0_LAB_BEGIN:CarryTool.sv_n_sendItem\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t__SMML_GP0_PROBE.mark( "carry.rpc.server", { rpc = "sv_n_sendItem", targetUuid = params and params.targetShape and params.targetShape:getShapeUuid() or "nil", itemUuid = params and params.itemA or "nil", playerId = player and player.id or "nil" } )\n\tend\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.lab ) == "table" and type( __SMML_GP0_PROBE.lab.onCarryRpc ) == "function" then\n\t\t__SMML_GP0_PROBE.lab.onCarryRpc( params, player )\n\tend\n\t-- SMML_GP0_LAB_END:CarryTool.sv_n_sendItem\n'''
        text = inject_after_once(text, "function CarryTool.sv_n_sendItem( self, params, player )\n", server_rpc, rel)

        server_harvest_rpc = '''\t-- SMML_GP0_LAB_BEGIN:CarryTool.sv_n_sendItemToHarvestable\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t__SMML_GP0_PROBE.mark( "carry.rpc.server", { rpc = "sv_n_sendItemToHarvestable", targetUuid = params and params.targetHarvestable and params.targetHarvestable.uuid or "nil", itemUuid = params and params.itemA or "nil", playerId = player and player.id or "nil" } )\n\tend\n\t-- SMML_GP0_LAB_END:CarryTool.sv_n_sendItemToHarvestable\n'''
        text = inject_after_once(text, "function CarryTool.sv_n_sendItemToHarvestable( self, params, player )\n", server_harvest_rpc, rel)

    elif rel == "Survival/Scripts/game/interactables/ResourceContainer.lua":
        recv = '''\t-- SMML_GP0_LAB_BEGIN:ResourceContainer.sv_e_receiveItem\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.mark ) == "function" then\n\t\t__SMML_GP0_PROBE.mark( "carry.receive.server", { targetUuid = self.shape:getShapeUuid(), itemUuid = params and params.itemA or "nil", playerId = params and params.player and params.player.id or "nil" } )\n\tend\n\tif type( __SMML_GP0_PROBE ) == "table" and type( __SMML_GP0_PROBE.lab ) == "table" and type( __SMML_GP0_PROBE.lab.onResourceReceive ) == "function" then\n\t\t__SMML_GP0_PROBE.lab.onResourceReceive( self, params )\n\tend\n\t-- SMML_GP0_LAB_END:ResourceContainer.sv_e_receiveItem\n'''
        text = inject_after_once(text, "function ResourceContainer.sv_e_receiveItem( self, params )\n", recv, rel)
    else:
        raise RuntimeError(f"No patch recipe for {rel}")

    if use_crlf:
        text = text.replace("\n", "\r\n")
    return text.encode("utf-8")


def verify_clean_root(root: Path) -> None:
    if not (root / "Survival").is_dir() or not (root / "Data").is_dir():
        raise SystemExit(f"Not a Scrap Mechanic root: {root}")
    problems: list[str] = []
    for rel, expected in TARGETS.items():
        p = root / rel
        if not p.is_file():
            problems.append(f"MISSING {rel}")
            continue
        actual = sha256_file(p)
        if actual != expected:
            problems.append(f"MODIFIED {rel}\n  expected {expected}\n  actual   {actual}")
    cache = root / CACHE_PATH
    if not cache.is_file():
        problems.append(f"MISSING {CACHE_PATH}")
    elif sha256_file(cache) != CACHE_SHA256:
        problems.append(f"MODIFIED {CACHE_PATH}\n  expected {CACHE_SHA256}\n  actual   {sha256_file(cache)}")
    for rel in list(RUNTIME_FILES) + [CONFIG_PATH]:
        if (root / rel).exists():
            problems.append(f"EXTRA {rel} already exists")
    if problems:
        raise SystemExit("Preflight failed:\n" + "\n".join(problems))


def snapshot_tree(source: Path, destination: Path) -> dict:
    if destination.exists():
        raise SystemExit(f"Snapshot destination already exists: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source, destination, symlinks=True)
    entries = []
    for p in sorted(destination.rglob("*")):
        rel = p.relative_to(destination).as_posix()
        if p.is_symlink():
            entries.append({"path": rel, "kind": "symlink", "target": os.readlink(p)})
        elif p.is_file():
            entries.append({"path": rel, "kind": "file", "size": p.stat().st_size, "sha256": sha256_file(p)})
        elif p.is_dir():
            entries.append({"path": rel, "kind": "dir"})
    manifest = {
        "schema": "smml-gp0-save-snapshot/1",
        "created_at_utc": utc_now(),
        "source": str(source),
        "entries": entries,
    }
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    atomic_write(destination.parent / "snapshot-manifest.json", manifest_bytes)
    manifest["manifest_sha256"] = sha256_bytes(manifest_bytes)
    return manifest


def verify_snapshot(snapshot_dir: Path, manifest: dict) -> list[str]:
    problems: list[str] = []
    for entry in manifest.get("entries", []):
        p = snapshot_dir / entry["path"]
        kind = entry["kind"]
        if kind == "file":
            if not p.is_file():
                problems.append(f"MISSING {entry['path']}")
            elif p.stat().st_size != entry["size"] or sha256_file(p) != entry["sha256"]:
                problems.append(f"DRIFT {entry['path']}")
        elif kind == "dir":
            if not p.is_dir():
                problems.append(f"MISSING DIR {entry['path']}")
        elif kind == "symlink":
            if not p.is_symlink() or os.readlink(p) != entry["target"]:
                problems.append(f"DRIFT SYMLINK {entry['path']}")
    return problems


def invalidate_current_cache(root: Path, state_dir: Path, state: dict, reason: str) -> None:
    cp = root / CACHE_PATH
    if cp.exists():
        quarantine = state_dir / "quarantine" / f"core_data.cbo.{reason}-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        quarantine.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(cp), str(quarantine))
        state.setdefault("cache", {}).setdefault("quarantined", []).append(str(quarantine))


def install(args: argparse.Namespace) -> None:
    require_game_stopped()
    root = args.game_root.expanduser().resolve()
    state_dir = args.state_dir.expanduser().resolve()
    if state_path(state_dir).exists():
        old = json.loads(state_path(state_dir).read_text("utf-8"))
        if old.get("installed"):
            raise SystemExit(f"Lab already installed according to {state_path(state_dir)}")
    verify_clean_root(root)

    package_dir = Path(__file__).resolve().parent
    backup_dir = state_dir / "backups"
    backup_dir.mkdir(parents=True, exist_ok=True)

    prepared: dict[str, bytes] = {}
    records: dict[str, dict] = {}
    for rel, expected in TARGETS.items():
        src = root / rel
        original = src.read_bytes()
        if sha256_bytes(original) != expected:
            raise SystemExit(f"Preflight changed during install: {rel}")
        patched = apply_patch(rel, original)
        prepared[rel] = patched
        backup = backup_dir / rel
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, backup)
        records[rel] = {
            "before_sha256": expected,
            "after_sha256": sha256_bytes(patched),
            "backup": str(backup),
        }

    cache_src = root / CACHE_PATH
    cache_backup = backup_dir / CACHE_PATH
    cache_backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(cache_src, cache_backup)

    runtime_records: dict[str, dict] = {}
    runtime_payloads: dict[str, bytes] = {}
    for target_rel, package_rel in RUNTIME_FILES.items():
        src = package_dir / package_rel
        if not src.is_file():
            raise SystemExit(f"Missing payload: {src}")
        data = src.read_bytes()
        runtime_payloads[target_rel] = data
        runtime_records[target_rel] = {"sha256": sha256_bytes(data), "source": package_rel}

    config_data = render_config(False, "DISARMED", manual_loadout=True)

    # Commit only after every patch and payload has been prepared.
    for rel, patched in prepared.items():
        atomic_write(root / rel, patched)
    for rel, data in runtime_payloads.items():
        atomic_write(root / rel, data)
    atomic_write(root / CONFIG_PATH, config_data)
    cache_src.unlink()

    state = {
        "schema": "smml-gp0-carry-storage-lab-state/1",
        "version": VERSION,
        "installed": True,
        "installed_at_utc": utc_now(),
        "installed_epoch": time.time(),
        "game_root": str(root),
        "files": records,
        "runtime_files": runtime_records,
        "config": {"path": CONFIG_PATH, "sha256": sha256_bytes(config_data), "enabled": False, "run_id": "DISARMED"},
        "cache": {"path": CACHE_PATH, "before_sha256": CACHE_SHA256, "backup": str(cache_backup), "quarantined": []},
        "lab": {"armed": False, "snapshot": None},
    }
    save_state(state_dir, state)
    print("[OK] SMML GP0 Carry/Storage Lab hooks installed (passive/disarmed)")
    print(f"State: {state_dir}")
    print(f"Targeted cache invalidated: {CACHE_PATH}")
    print("Next: arm the lab with a recursive Save snapshot before launching the test world.")


def verify_installed_files(state: dict) -> list[str]:
    root = Path(state["game_root"])
    problems = []
    for rel, rec in state.get("files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec["after_sha256"]:
            problems.append(f"DRIFT {rel}")
    for rel, rec in state.get("runtime_files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec["sha256"]:
            problems.append(f"DRIFT {rel}")
    cp = root / state["config"]["path"]
    if not cp.is_file() or sha256_file(cp) != state["config"]["sha256"]:
        problems.append(f"DRIFT {state['config']['path']}")
    return problems


def arm(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("Lab hooks are not installed.")
    if state.get("lab", {}).get("armed"):
        raise SystemExit("Lab is already armed.")
    problems = verify_installed_files(state)
    if problems:
        raise SystemExit("Arm refused because installed files drifted:\n" + "\n".join(problems))

    save_root = args.save_root.expanduser().resolve()
    if not save_root.is_dir():
        raise SystemExit(f"Save root is not a directory: {save_root}")

    run_id = datetime.now().strftime("GP0-%Y%m%d-%H%M%S")
    snapshot_parent = state_dir / "snapshots" / run_id
    snapshot_dir = snapshot_parent / "Save"
    manifest = snapshot_tree(save_root, snapshot_dir)
    problems = verify_snapshot(snapshot_dir, manifest)
    if problems:
        raise SystemExit("Snapshot verification failed:\n" + "\n".join(problems[:20]))

    root = Path(state["game_root"])
    config_data = render_config(True, run_id, manual_loadout=not args.no_manual_loadout)
    atomic_write(root / CONFIG_PATH, config_data)
    state["config"] = {"path": CONFIG_PATH, "sha256": sha256_bytes(config_data), "enabled": True, "run_id": run_id}
    state["lab"] = {
        "armed": True,
        "armed_at_utc": utc_now(),
        "armed_epoch": time.time(),
        "run_id": run_id,
        "save_root": str(save_root),
        "snapshot": {
            "dir": str(snapshot_dir),
            "manifest": manifest,
            "restored": False,
        },
    }
    invalidate_current_cache(root, state_dir, state, "arm")
    save_state(state_dir, state)

    print(f"[OK] Lab armed: {run_id}")
    print(f"Recursive Save snapshot: {snapshot_dir}")
    print(f"Snapshot files/dirs: {len(manifest['entries'])}")
    print("Next: launch Scrap Mechanic normally (without -dev) and enter/create the dedicated Survival test world.")


def status(args: argparse.Namespace) -> None:
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    root = Path(state["game_root"])
    print(f"Lab version: {state.get('version')}")
    print(f"Installed: {state.get('installed')}")
    print(f"Armed: {state.get('lab', {}).get('armed')}")
    print(f"Run ID: {state.get('lab', {}).get('run_id')}")
    print(f"Game root: {root}")
    for rel, rec in state.get("files", {}).items():
        p = root / rel
        current = sha256_file(p) if p.is_file() else None
        label = "PATCHED" if current == rec.get("after_sha256") else "RESTORED" if current == rec.get("before_sha256") else "DRIFT"
        print(f"{label:8} {rel}")
    for rel, rec in state.get("runtime_files", {}).items():
        p = root / rel
        current = sha256_file(p) if p.is_file() else None
        label = "PRESENT" if current == rec.get("sha256") else "ABSENT" if current is None else "DRIFT"
        print(f"{label:8} {rel}")
    cfg = root / state["config"]["path"]
    cfg_hash = sha256_file(cfg) if cfg.is_file() else None
    print(f"CONFIG   enabled={state['config'].get('enabled')} sha256={cfg_hash}")
    cp = root / CACHE_PATH
    print(f"CACHE    {'present sha256=' + sha256_file(cp) if cp.is_file() else 'absent'}")
    snap = state.get("lab", {}).get("snapshot")
    if snap:
        print(f"SNAPSHOT {snap['dir']} restored={snap.get('restored')}")


def parse_event_line(line: str) -> dict | None:
    if MARKER not in line:
        return None
    payload = line[line.index(MARKER):].strip()
    parts = payload.split("|")
    result = {"raw": payload}
    if parts:
        result["record"] = parts[0].replace(MARKER, "").strip()
    for part in parts[1:]:
        if "=" in part:
            k, v = part.split("=", 1)
            result[k.strip()] = v.strip()
    return result


def collect_data(state_dir: Path, output: Path) -> dict:
    state = load_state(state_dir)
    root = Path(state["game_root"])
    logs_dir = root / "Logs"
    since = float(state.get("lab", {}).get("armed_epoch") or state.get("installed_epoch", 0))

    candidates = []
    if logs_dir.is_dir():
        for p in sorted(logs_dir.glob("game-*.log")):
            try:
                if p.stat().st_mtime >= since - 60:
                    candidates.append(p)
            except OSError:
                pass

    events = []
    diagnostics = []
    for p in candidates:
        text = p.read_text("utf-8", errors="replace")
        for line_no, line in enumerate(text.splitlines(), 1):
            parsed = parse_event_line(line)
            if parsed:
                parsed["source_log"] = p.name
                parsed["line"] = line_no
                events.append(parsed)
            if any(x in line for x in ("[Lua] ERROR:", "Failed to load file:", "Load failed", "SMMLProbe", MARKER)):
                diagnostics.append({"source_log": p.name, "line": line_no, "text": line})

    storage_rows = [e for e in events if e.get("event") == "storage.case"]
    carry_rows = [e for e in events if e.get("event") in {
        "carry.tryInsert.begin", "carry.raycast", "carry.target", "carry.branch",
        "carry.rpc.client", "carry.rpc.server", "carry.receive.server", "carry.case"
    }]

    event_counts = Counter(e.get("event", "") for e in events)
    carry_success = any(e.get("event") == "carry.case" and e.get("success") == "true" for e in events)
    expected_storage_cases = 16 * 13
    summary = {
        "schema": "smml-gp0-carry-storage-lab-results/1",
        "version": state.get("version"),
        "run_id": state.get("lab", {}).get("run_id"),
        "collected_at_utc": utc_now(),
        "candidate_logs": [p.name for p in candidates],
        "event_count": len(events),
        "event_counts": dict(event_counts),
        "storage_cases_expected": expected_storage_cases,
        "storage_cases_observed": len(storage_rows),
        "storage_matrix_complete": len(storage_rows) == expected_storage_cases,
        "carry_success": carry_success,
        "carry_rpc_server_seen": any(e.get("event") == "carry.rpc.server" and e.get("rpc") == "sv_n_sendItem" for e in events),
        "carry_receive_server_seen": any(e.get("event") == "carry.receive.server" for e in events),
        "lab_complete_seen": any(e.get("event") == "carry.case" and e.get("success") == "true" for e in events),
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        zf.writestr("summary.json", json.dumps(summary, indent=2, sort_keys=True))
        zf.writestr("state.json", json.dumps(state, indent=2, sort_keys=True))
        zf.writestr("events.json", json.dumps(events, indent=2, sort_keys=True))
        zf.writestr("probe-lines.txt", "\n".join(e["raw"] for e in events) + ("\n" if events else ""))
        zf.writestr("diagnostic-lines.txt", "\n".join(f"{d['source_log']}:{d['line']}: {d['text']}" for d in diagnostics) + ("\n" if diagnostics else ""))

        if events:
            keys = sorted({k for e in events for k in e.keys() if k != "raw"})
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=keys, extrasaction="ignore")
            w.writeheader()
            for e in events:
                w.writerow({k: e.get(k, "") for k in keys})
            zf.writestr("events.csv", buf.getvalue())

        if storage_rows:
            preferred = [
                "fixtureId", "fixtureTitle", "fixtureUuid", "expectedSlots", "actualSlots",
                "itemId", "itemTitle", "itemUuid", "ready", "canCollect", "beginTransaction",
                "dryRunCollected", "abortIssued", "beforeQuantity", "afterQuantity",
                "unchangedAfterAbort", "revisionBefore", "revisionAfter", "error", "source_log", "line"
            ]
            keys = preferred + sorted({k for r in storage_rows for k in r if k not in set(preferred) | {"raw", "record", "event", "seq", "runtime", "version", "fileLoads", "initCount", "bootstrapCalls", "host"}})
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=keys, extrasaction="ignore")
            w.writeheader()
            for row in storage_rows:
                w.writerow({k: row.get(k, "") for k in keys})
            zf.writestr("storage-matrix.csv", buf.getvalue())

        if carry_rows:
            keys = sorted({k for r in carry_rows for k in r if k != "raw"})
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=keys, extrasaction="ignore")
            w.writeheader()
            for row in carry_rows:
                w.writerow({k: row.get(k, "") for k in keys})
            zf.writestr("carry-matrix.csv", buf.getvalue())

        snap = state.get("lab", {}).get("snapshot")
        if snap:
            zf.writestr("snapshot-manifest.json", json.dumps(snap.get("manifest", {}), indent=2, sort_keys=True))

        for p in candidates:
            zf.write(p, f"raw-logs/{p.name}")

    return summary


def collect(args: argparse.Namespace) -> None:
    state_dir = args.state_dir.expanduser().resolve()
    output = args.output.expanduser().resolve() if args.output else Path.cwd() / f"smml-gp0-lab-results-{datetime.now().strftime('%Y%m%d-%H%M%S')}.zip"
    summary = collect_data(state_dir, output)
    print(f"[OK] Collected {summary['event_count']} events")
    print(f"Storage matrix: {summary['storage_cases_observed']}/{summary['storage_cases_expected']}")
    print(f"Carry success: {summary['carry_success']}")
    print(output)


def disable_config(state_dir: Path, state: dict, reason: str) -> None:
    root = Path(state["game_root"])
    data = render_config(False, "DISARMED", manual_loadout=True)
    atomic_write(root / CONFIG_PATH, data)
    state["config"] = {"path": CONFIG_PATH, "sha256": sha256_bytes(data), "enabled": False, "run_id": "DISARMED"}
    state.setdefault("lab", {})["armed"] = False
    state["lab"]["disarmed_at_utc"] = utc_now()
    invalidate_current_cache(root, state_dir, state, reason)


def disarm(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("Lab hooks are not installed.")
    disable_config(state_dir, state, "disarm")
    save_state(state_dir, state)
    print("[OK] Lab disarmed. Save changes were kept; use restore-save to revert the test world/data.")


def restore_save_internal(state_dir: Path, state: dict) -> None:
    lab_state = state.get("lab", {})
    snap = lab_state.get("snapshot")
    if not snap:
        raise SystemExit("No Save snapshot is recorded in this state.")
    if snap.get("restored"):
        return

    snapshot_dir = Path(snap["dir"])
    manifest = snap["manifest"]
    problems = verify_snapshot(snapshot_dir, manifest)
    if problems:
        raise SystemExit("Snapshot integrity failure:\n" + "\n".join(problems[:20]))

    save_root = Path(lab_state["save_root"])
    quarantine = state_dir / "quarantine" / f"Save.post-lab-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    quarantine.parent.mkdir(parents=True, exist_ok=True)
    if save_root.exists():
        shutil.move(str(save_root), str(quarantine))
    shutil.copytree(snapshot_dir, save_root, symlinks=True)

    # Verify restored bytes against snapshot manifest.
    restore_problems = []
    for entry in manifest.get("entries", []):
        p = save_root / entry["path"]
        if entry["kind"] == "file":
            if not p.is_file() or p.stat().st_size != entry["size"] or sha256_file(p) != entry["sha256"]:
                restore_problems.append(entry["path"])
        elif entry["kind"] == "dir" and not p.is_dir():
            restore_problems.append(entry["path"])
        elif entry["kind"] == "symlink" and (not p.is_symlink() or os.readlink(p) != entry["target"]):
            restore_problems.append(entry["path"])
    if restore_problems:
        raise SystemExit("Restored Save verification failed: " + ", ".join(restore_problems[:20]))

    snap["restored"] = True
    snap["restored_at_utc"] = utc_now()
    snap["post_lab_quarantine"] = str(quarantine)
    disable_config(state_dir, state, "restore-save")


def restore_save(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    restore_save_internal(state_dir, state)
    save_state(state_dir, state)
    print("[OK] Recursive Save snapshot restored and verified. Post-lab Save tree was quarantined.")


def uninstall_internal(state_dir: Path, state: dict) -> None:
    root = Path(state["game_root"])
    if state.get("lab", {}).get("armed"):
        raise SystemExit("Uninstall refused while the lab is armed. Run restore-save or disarm first.")

    problems = []
    for rel, rec in state.get("files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec["after_sha256"]:
            problems.append(f"DRIFT {rel}")
    for rel, rec in state.get("runtime_files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec["sha256"]:
            problems.append(f"DRIFT {rel}")
    cfg = root / CONFIG_PATH
    if not cfg.is_file() or sha256_file(cfg) != state["config"]["sha256"]:
        problems.append(f"DRIFT {CONFIG_PATH}")
    if problems:
        raise SystemExit("Uninstall refused because owned files drifted:\n" + "\n".join(problems))

    for rel, rec in state.get("files", {}).items():
        backup = Path(rec["backup"])
        data = backup.read_bytes()
        if sha256_bytes(data) != rec["before_sha256"]:
            raise SystemExit(f"Backup integrity failure: {backup}")
        atomic_write(root / rel, data)

    for rel in list(state.get("runtime_files", {})) + [CONFIG_PATH]:
        p = root / rel
        if p.exists():
            p.unlink()
    try:
        (root / PROBE_DIR).rmdir()
    except OSError:
        pass

    cp = root / CACHE_PATH
    if cp.exists():
        quarantine = state_dir / "quarantine" / f"core_data.cbo.post-lab-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
        quarantine.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(cp), str(quarantine))
        state["cache"].setdefault("quarantined", []).append(str(quarantine))
    cache_backup = Path(state["cache"]["backup"])
    if sha256_file(cache_backup) != state["cache"]["before_sha256"]:
        raise SystemExit(f"Cache backup integrity failure: {cache_backup}")
    atomic_write(cp, cache_backup.read_bytes())

    failures = []
    for rel, rec in state.get("files", {}).items():
        if sha256_file(root / rel) != rec["before_sha256"]:
            failures.append(rel)
    if sha256_file(cp) != state["cache"]["before_sha256"]:
        failures.append(CACHE_PATH)
    if failures:
        raise SystemExit("Restoration verification failed: " + ", ".join(failures))

    state["installed"] = False
    state["uninstalled_at_utc"] = utc_now()


def uninstall(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("State says the lab is not installed.")
    uninstall_internal(state_dir, state)
    save_state(state_dir, state)
    print("[OK] Hooks/runtime removed; vanilla Lua files and core_data.cbo restored byte-for-byte.")


def finish(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    output = args.output.expanduser().resolve() if args.output else Path.cwd() / f"smml-gp0-lab-results-{datetime.now().strftime('%Y%m%d-%H%M%S')}.zip"
    summary = collect_data(state_dir, output)
    restore_save_internal(state_dir, state)
    uninstall_internal(state_dir, state)
    state["finish"] = {"at_utc": utc_now(), "results": str(output), "summary": summary}
    save_state(state_dir, state)
    print(f"[OK] Results collected: {output}")
    print("[OK] Save snapshot restored and hooks removed.")
    print(f"Storage matrix: {summary['storage_cases_observed']}/{summary['storage_cases_expected']}; carry success={summary['carry_success']}")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="SMML GP0.2 Carry / Storage Laboratory")
    p.add_argument("--state-dir", type=Path, default=default_state_dir(), help="Persistent lab state directory")
    sub = p.add_subparsers(dest="command", required=True)

    i = sub.add_parser("install", help="Install passive hooks and runtime; lab remains disarmed")
    i.add_argument("game_root", type=Path)
    i.set_defaults(func=install)

    a = sub.add_parser("arm", help="Snapshot the entire Save tree and enable the lab")
    a.add_argument("--save-root", type=Path, required=True, help="Exact Scrap Mechanic Save directory to snapshot recursively")
    a.add_argument("--no-manual-loadout", action="store_true", help="Run automatic matrices but do not add manual test items")
    a.set_defaults(func=arm)

    s = sub.add_parser("status", help="Show hook, runtime, cache, arm and snapshot state")
    s.set_defaults(func=status)

    c = sub.add_parser("collect", help="Collect logs and generate storage/carry CSV matrices")
    c.add_argument("--output", type=Path)
    c.set_defaults(func=collect)

    d = sub.add_parser("disarm", help="Disable future lab mutation but keep current Save changes")
    d.set_defaults(func=disarm)

    r = sub.add_parser("restore-save", help="Restore and verify the recursive pre-lab Save snapshot")
    r.set_defaults(func=restore_save)

    u = sub.add_parser("uninstall", help="Restore exact vanilla Lua/cache; refuses while armed")
    u.set_defaults(func=uninstall)

    f = sub.add_parser("finish", help="Collect results, restore Save snapshot, then uninstall hooks")
    f.add_argument("--output", type=Path)
    f.set_defaults(func=finish)
    return p


def main() -> int:
    args = build_parser().parse_args()
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
