#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import os
import shutil
import sys
import time
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

VERSION = "0.2.0"
MARKER = "[SMML-GP0-NS]"
TARGET = "Survival/Scripts/game/SurvivalGame.lua"
TARGET_SHA256 = "934beb15dff2f34638128a56aa1be8586e363bc1a5d564698e9b8f09bf9d35c4"
CACHE_PATH = "Cache/Bundle/core_data.cbo"
PROBE_DIR = "Survival/Scripts/SMMLProbeNS"
RUNTIME_FILES = {
    f"{PROBE_DIR}/Runtime.lua": "payload/Runtime.lua",
    f"{PROBE_DIR}/Probe.lua": "payload/Probe.lua",
}
CONFIG_PATH = f"{PROBE_DIR}/ProbeConfig.lua"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + f".tmp-{os.getpid()}")
    with tmp.open("wb") as f:
        f.write(data)
        f.flush()
        os.fsync(f.fileno())
    os.replace(tmp, path)


def default_state_dir() -> Path:
    override = os.environ.get("SMML_GP0_NS_STATE")
    if override:
        return Path(override).expanduser()
    base = os.environ.get("XDG_STATE_HOME")
    if base:
        return Path(base) / "smml" / "gp0-network-storage-probe"
    return Path.home() / ".local" / "state" / "smml" / "gp0-network-storage-probe"


def is_relative_to(child: Path, parent: Path) -> bool:
    try:
        child.relative_to(parent)
        return True
    except ValueError:
        return False


def assert_disjoint(a: Path, b: Path, a_name: str, b_name: str) -> None:
    ar = a.resolve()
    br = b.resolve()
    if ar == br or is_relative_to(ar, br) or is_relative_to(br, ar):
        raise SystemExit(f"Unsafe overlapping roots: {a_name}={ar} {b_name}={br}")


def reject_symlink(path: Path, label: str) -> None:
    if path.is_symlink():
        raise SystemExit(f"Symlink/reparse-style path refused for {label}: {path}")


def game_running() -> list[str]:
    hits: list[str] = []
    proc = Path("/proc")
    if not proc.is_dir():
        return hits
    for child in proc.iterdir():
        if not child.name.isdigit():
            continue
        try:
            cmd = (child / "cmdline").read_bytes().replace(b"\0", b" ").decode("utf-8", "ignore")
            comm = (child / "comm").read_text("utf-8", errors="ignore").strip()
        except OSError:
            continue
        hay = (comm + " " + cmd).lower()
        if "scrapmechanic.exe" in hay or "scrap mechanic/release/scrapmechanic" in hay:
            hits.append(f"pid={child.name} {comm} {cmd[:220]}")
    return hits


def require_game_stopped() -> None:
    hits = game_running()
    if hits:
        raise SystemExit("Scrap Mechanic appears to be running:\n" + "\n".join(hits))


def state_path(state_dir: Path) -> Path:
    return state_dir / "state.json"


def load_state(state_dir: Path) -> dict:
    path = state_path(state_dir)
    if not path.is_file():
        raise SystemExit(f"Probe state not found: {path}")
    state = json.loads(path.read_text("utf-8"))
    if state.get("schema") != "smml-gp0-network-storage-probe-state/1":
        raise SystemExit(f"Unsupported or foreign state schema: {state.get('schema')}")
    return state


def save_state(state_dir: Path, state: dict) -> None:
    state_dir.mkdir(parents=True, exist_ok=True)
    atomic_write(state_path(state_dir), (json.dumps(state, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def lua_bool(value: bool) -> str:
    return "true" if value else "false"


def render_config(enabled: bool, role: str, run_id: str) -> bytes:
    if role not in {"disabled", "host", "client"}:
        raise ValueError(role)
    text = f'''-- Generated by smml_gp0_network_storage_probe.py v{VERSION}.\n__SMML_GP0_NS_CONFIG = {{\n    enabled = {lua_bool(enabled)},\n    role = "{role}",\n    runId = "{run_id}"\n}}\nreturn __SMML_GP0_NS_CONFIG\n'''
    return text.encode("utf-8")


def ensure_prefix() -> str:
    return f'''-- SMML_GP0_NS_BEGIN:bootstrap\nlocal function __smml_gp0_ns_ensureRuntime( source )\n    if type( __SMML_GP0_NS ) ~= "table" or __SMML_GP0_NS.version ~= "{VERSION}" then\n        if type( pcall ) == "function" then\n            local ok, err = pcall( dofile, "$SURVIVAL_DATA/Scripts/SMMLProbeNS/Runtime.lua" )\n            if not ok and type( sm ) == "table" and type( sm.log ) == "table" and type( sm.log.error ) == "function" then\n                sm.log.error( "[SMML-GP0-NS] FALLBACK|event=runtime.load.error|source=" .. tostring( source ) .. "|detail=" .. tostring( err ) )\n            end\n        end\n    end\n    if type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.bootstrap ) == "function" then\n        __SMML_GP0_NS.bootstrap( source )\n        return true\n    end\n    return false\nend\n__smml_gp0_ns_ensureRuntime( "SurvivalGame.lua.file" )\n-- SMML_GP0_NS_END:bootstrap\n'''


def inject_after_once(text: str, anchor: str, insertion: str, label: str) -> str:
    count = text.count(anchor)
    if count != 1:
        raise RuntimeError(f"{label}: expected one anchor, found {count}: {anchor!r}")
    return text.replace(anchor, anchor + insertion, 1)


def apply_patch(original: bytes) -> bytes:
    use_crlf = b"\r\n" in original and original.count(b"\r\n") == original.count(b"\n")
    text = original.decode("utf-8")
    if use_crlf:
        text = text.replace("\r\n", "\n")

    text = ensure_prefix() + text

    def cb(method: str, body: str) -> None:
        nonlocal text
        anchor = f"function SurvivalGame.{method}"
        if method in {"server_onCreate", "server_onDestroy", "server_onUnload"}:
            full = anchor + "( self )\n"
        elif method == "client_onCreate":
            full = anchor + "( self )\n"
        elif method == "client_onClientDataUpdate":
            full = anchor + "( self, clientData, channel )\n"
        elif method == "server_onFixedUpdate":
            full = anchor + "( self, timeStep )\n"
        elif method == "client_onUpdate":
            full = anchor + "( self, dt )\n"
        elif method == "server_onPlayerJoined":
            full = anchor + "( self, player, newPlayer )\n"
        elif method == "server_onPlayerLeft":
            full = anchor + "( self, player )\n"
        else:
            raise AssertionError(method)
        text = inject_after_once(text, full, body, TARGET)

    cb("server_onCreate", '''\t-- SMML_GP0_NS_BEGIN:server_onCreate\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerCreate ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerCreate, self )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onCreate", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onCreate\n''')
    cb("server_onDestroy", '''\t-- SMML_GP0_NS_BEGIN:server_onDestroy\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerDestroy ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerDestroy, self )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onDestroy", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onDestroy\n''')
    cb("server_onUnload", '''\t-- SMML_GP0_NS_BEGIN:server_onUnload\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerUnload ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerUnload, self )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onUnload", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onUnload\n''')
    cb("client_onCreate", '''\t-- SMML_GP0_NS_BEGIN:client_onCreate\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onClientCreate ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onClientCreate, self )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "client_onCreate", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:client_onCreate\n''')
    cb("client_onClientDataUpdate", '''\t-- SMML_GP0_NS_BEGIN:client_onClientDataUpdate\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onClientDataUpdate ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onClientDataUpdate, self, clientData, channel )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "client_onClientDataUpdate", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:client_onClientDataUpdate\n''')
    cb("server_onFixedUpdate", '''\t-- SMML_GP0_NS_BEGIN:server_onFixedUpdate\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerFixedUpdate ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerFixedUpdate, self, timeStep )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onFixedUpdate", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onFixedUpdate\n''')
    cb("client_onUpdate", '''\t-- SMML_GP0_NS_BEGIN:client_onUpdate\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onClientUpdate ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onClientUpdate, self, dt )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "client_onUpdate", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:client_onUpdate\n''')
    cb("server_onPlayerJoined", '''\t-- SMML_GP0_NS_BEGIN:server_onPlayerJoined\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerPlayerJoined ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerPlayerJoined, self, player, newPlayer )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onPlayerJoined", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onPlayerJoined\n''')
    cb("server_onPlayerLeft", '''\t-- SMML_GP0_NS_BEGIN:server_onPlayerLeft\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerPlayerLeft ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerPlayerLeft, self, player )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "server_onPlayerLeft", detail = err } ) end\n\tend\n\t-- SMML_GP0_NS_END:server_onPlayerLeft\n''')

    text += '''\n-- SMML_GP0_NS_BEGIN:network_methods\nfunction SurvivalGame.sv_smmlGp0ProbeEnvelope( self, envelope, player )\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onServerEnvelope ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onServerEnvelope, self, envelope, player )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "sv_smmlGp0ProbeEnvelope", detail = err } ) end\n\tend\nend\n\nfunction SurvivalGame.cl_smmlGp0ProbeReply( self, params )\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onClientReply ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onClientReply, self, params )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "cl_smmlGp0ProbeReply", detail = err } ) end\n\tend\nend\n\nfunction SurvivalGame.cl_smmlGp0ProbeBroadcast( self, params )\n\tif type( __SMML_GP0_NS ) == "table" and type( __SMML_GP0_NS.ns ) == "table" and type( __SMML_GP0_NS.ns.onClientBroadcast ) == "function" then\n\t\tlocal ok, err = pcall( __SMML_GP0_NS.ns.onClientBroadcast, self, params )\n\t\tif not ok and type( __SMML_GP0_NS.mark ) == "function" then __SMML_GP0_NS.mark( "hook.error", { hook = "cl_smmlGp0ProbeBroadcast", detail = err } ) end\n\tend\nend\n-- SMML_GP0_NS_END:network_methods\n'''

    if use_crlf:
        text = text.replace("\n", "\r\n")
    return text.encode("utf-8")


def validate_game_root(root: Path) -> None:
    if not root.is_dir() or not (root / "Survival").is_dir() or not (root / "Data").is_dir():
        raise SystemExit(f"Not a Scrap Mechanic root: {root}")
    reject_symlink(root, "game root")
    target = root / TARGET
    reject_symlink(target, TARGET)
    if not target.is_file():
        raise SystemExit(f"Missing target: {target}")
    actual = sha256_file(target)
    if actual != TARGET_SHA256:
        raise SystemExit(
            f"Preflight failed: {TARGET} is not the clean 1.0.6.889 baseline.\n"
            f"  expected {TARGET_SHA256}\n  actual   {actual}\n"
            "Restore/uninstall any previous probe before installing this one."
        )
    for rel in list(RUNTIME_FILES) + [CONFIG_PATH]:
        if (root / rel).exists():
            raise SystemExit(f"Preflight failed: owned probe path already exists: {rel}")


def invalidate_cache(root: Path, state_dir: Path, state: dict, reason: str) -> None:
    cache = root / CACHE_PATH
    if cache.exists():
        reject_symlink(cache, CACHE_PATH)
        quarantine = state_dir / "quarantine" / f"core_data.cbo.{reason}-{datetime.now().strftime('%Y%m%d-%H%M%S-%f')}"
        quarantine.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(cache), str(quarantine))
        state.setdefault("cache", {}).setdefault("quarantined", []).append(str(quarantine))


def install(args: argparse.Namespace) -> None:
    require_game_stopped()
    root = args.game_root.expanduser().resolve()
    state_dir = args.state_dir.expanduser().resolve()
    assert_disjoint(root, state_dir, "game_root", "state_dir")
    validate_game_root(root)
    if state_path(state_dir).exists():
        old = json.loads(state_path(state_dir).read_text("utf-8"))
        if old.get("installed"):
            raise SystemExit(f"Probe already installed according to {state_path(state_dir)}")

    package_dir = Path(__file__).resolve().parent
    backup_dir = state_dir / "backups"
    backup_dir.mkdir(parents=True, exist_ok=True)

    original = (root / TARGET).read_bytes()
    patched = apply_patch(original)
    target_backup = backup_dir / TARGET
    target_backup.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(root / TARGET, target_backup)

    runtime_records: dict[str, dict] = {}
    runtime_payloads: dict[str, bytes] = {}
    for target_rel, package_rel in RUNTIME_FILES.items():
        src = package_dir / package_rel
        if not src.is_file():
            raise SystemExit(f"Missing payload: {src}")
        data = src.read_bytes()
        runtime_payloads[target_rel] = data
        runtime_records[target_rel] = {"sha256": sha256_bytes(data), "source": package_rel}

    config_data = render_config(False, "disabled", "DISARMED")

    cache = root / CACHE_PATH
    cache_record = {"path": CACHE_PATH, "existed": cache.is_file(), "quarantined": []}
    if cache.is_file():
        reject_symlink(cache, CACHE_PATH)
        cache_backup = backup_dir / CACHE_PATH
        cache_backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(cache, cache_backup)
        cache_record.update({"before_sha256": sha256_file(cache), "backup": str(cache_backup)})

    state = {
        "schema": "smml-gp0-network-storage-probe-state/1",
        "version": VERSION,
        "installed": False,
        "phase": "prepared",
        "prepared_at_utc": utc_now(),
        "game_root": str(root),
        "files": {
            TARGET: {
                "before_sha256": TARGET_SHA256,
                "after_sha256": sha256_bytes(patched),
                "backup": str(target_backup),
            }
        },
        "runtime_files": runtime_records,
        "config": {
            "path": CONFIG_PATH,
            "sha256": sha256_bytes(config_data),
            "enabled": False,
            "role": "disabled",
            "run_id": "DISARMED",
        },
        "cache": cache_record,
        "probe": {"armed": False, "role": None, "run_id": None, "snapshot": None},
    }
    save_state(state_dir, state)

    atomic_write(root / TARGET, patched)
    for rel, data in runtime_payloads.items():
        atomic_write(root / rel, data)
    atomic_write(root / CONFIG_PATH, config_data)
    invalidate_cache(root, state_dir, state, "install")

    state["installed"] = True
    state["phase"] = "installed"
    state["installed_at_utc"] = utc_now()
    state["installed_epoch"] = time.time()
    save_state(state_dir, state)

    print("[OK] SMML GP0.5 Network/Storage probe installed (passive/disarmed)")
    print(f"Game:  {root}")
    print(f"State: {state_dir}")
    print(f"Patched: {TARGET}")
    print(f"Targeted cache invalidated: {CACHE_PATH}")


def verify_installed_files(state: dict) -> list[str]:
    root = Path(state["game_root"]).resolve()
    problems: list[str] = []
    for rel, rec in state.get("files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec.get("after_sha256"):
            problems.append(f"DRIFT {rel}")
    for rel, rec in state.get("runtime_files", {}).items():
        p = root / rel
        if not p.is_file() or sha256_file(p) != rec.get("sha256"):
            problems.append(f"DRIFT {rel}")
    cfg = root / state["config"]["path"]
    if not cfg.is_file() or sha256_file(cfg) != state["config"].get("sha256"):
        problems.append(f"DRIFT {state['config']['path']}")
    return problems


def snapshot_tree(source: Path, destination: Path) -> dict:
    if destination.exists():
        raise SystemExit(f"Snapshot destination already exists: {destination}")
    reject_symlink(source, "save root")
    for p in source.rglob("*"):
        if p.is_symlink():
            raise SystemExit(f"Save snapshot refused because a symlink exists: {p}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copytree(source, destination, symlinks=False)
    entries = []
    for p in sorted(destination.rglob("*")):
        rel = p.relative_to(destination).as_posix()
        if p.is_file():
            entries.append({"path": rel, "kind": "file", "size": p.stat().st_size, "sha256": sha256_file(p)})
        elif p.is_dir():
            entries.append({"path": rel, "kind": "dir"})
    manifest = {
        "schema": "smml-gp0-save-snapshot/1",
        "created_at_utc": utc_now(),
        "source": str(source),
        "entries": entries,
    }
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    atomic_write(destination.parent / "snapshot-manifest.json", manifest_bytes)
    manifest["manifest_sha256"] = sha256_bytes(manifest_bytes)
    return manifest


def verify_snapshot(snapshot_dir: Path, manifest: dict) -> list[str]:
    problems: list[str] = []
    for entry in manifest.get("entries", []):
        p = snapshot_dir / entry["path"]
        if entry["kind"] == "file":
            if not p.is_file() or p.stat().st_size != entry["size"] or sha256_file(p) != entry["sha256"]:
                problems.append(f"DRIFT {entry['path']}")
        elif entry["kind"] == "dir" and not p.is_dir():
            problems.append(f"MISSING DIR {entry['path']}")
    return problems


def arm_common(state_dir: Path, state: dict, role: str, run_id: str) -> None:
    root = Path(state["game_root"]).resolve()
    problems = verify_installed_files(state)
    if problems:
        raise SystemExit("Arm refused because installed files drifted:\n" + "\n".join(problems))
    config_data = render_config(True, role, run_id)
    atomic_write(root / CONFIG_PATH, config_data)
    state["config"] = {
        "path": CONFIG_PATH,
        "sha256": sha256_bytes(config_data),
        "enabled": True,
        "role": role,
        "run_id": run_id,
    }
    state["probe"]["armed"] = True
    state["probe"]["role"] = role
    state["probe"]["run_id"] = run_id
    state["probe"]["armed_at_utc"] = utc_now()
    state["probe"]["armed_epoch"] = time.time()
    invalidate_cache(root, state_dir, state, f"arm-{role}")


def arm_host(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("Probe is not installed.")
    if state.get("probe", {}).get("armed"):
        raise SystemExit("Probe is already armed.")

    root = Path(state["game_root"]).resolve()
    save_root = args.save_root.expanduser().resolve()
    if not save_root.is_dir():
        raise SystemExit(f"Save root is not a directory: {save_root}")
    assert_disjoint(root, state_dir, "game_root", "state_dir")
    assert_disjoint(save_root, state_dir, "save_root", "state_dir")
    assert_disjoint(root, save_root, "game_root", "save_root")

    run_id = args.run_id or datetime.now().strftime("GP05-%Y%m%d-%H%M%S")
    snapshot_parent = state_dir / "snapshots" / run_id
    snapshot_dir = snapshot_parent / "Save"
    manifest = snapshot_tree(save_root, snapshot_dir)
    problems = verify_snapshot(snapshot_dir, manifest)
    if problems:
        raise SystemExit("Snapshot verification failed:\n" + "\n".join(problems[:20]))

    arm_common(state_dir, state, "host", run_id)
    state["probe"]["save_root"] = str(save_root)
    state["probe"]["snapshot"] = {"dir": str(snapshot_dir), "manifest": manifest, "restored": False}
    save_state(state_dir, state)

    print(f"[OK] Host probe armed: {run_id}")
    print(f"Recursive Save snapshot: {snapshot_dir}")
    print("Use the SAME run ID when arming the client instance.")


def arm_client(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("Probe is not installed.")
    if state.get("probe", {}).get("armed"):
        raise SystemExit("Probe is already armed.")
    arm_common(state_dir, state, "client", args.run_id)
    state["probe"]["snapshot"] = None
    save_state(state_dir, state)
    print(f"[OK] Client probe armed: {args.run_id}")


def status(args: argparse.Namespace) -> None:
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    root = Path(state["game_root"]).resolve()
    print(f"Probe version: {state.get('version')}")
    print(f"Installed: {state.get('installed')}")
    print(f"Phase: {state.get('phase')}")
    print(f"Armed: {state.get('probe', {}).get('armed')}")
    print(f"Role: {state.get('probe', {}).get('role')}")
    print(f"Run ID: {state.get('probe', {}).get('run_id')}")
    print(f"Game root: {root}")
    for rel, rec in state.get("files", {}).items():
        p = root / rel
        current = sha256_file(p) if p.is_file() else None
        label = "PATCHED" if current == rec.get("after_sha256") else "RESTORED" if current == rec.get("before_sha256") else "DRIFT"
        print(f"{label:8} {rel}")
    for rel, rec in state.get("runtime_files", {}).items():
        p = root / rel
        current = sha256_file(p) if p.is_file() else None
        label = "PRESENT" if current == rec.get("sha256") else "ABSENT" if current is None else "DRIFT"
        print(f"{label:8} {rel}")
    cfg = root / state["config"]["path"]
    cfg_hash = sha256_file(cfg) if cfg.is_file() else None
    print(f"CONFIG   enabled={state['config'].get('enabled')} role={state['config'].get('role')} sha256={cfg_hash}")
    cp = root / CACHE_PATH
    print(f"CACHE    {'present sha256=' + sha256_file(cp) if cp.is_file() else 'absent'}")
    snap = state.get("probe", {}).get("snapshot")
    if snap:
        print(f"SNAPSHOT {snap['dir']} restored={snap.get('restored')}")


def parse_event_line(line: str) -> dict | None:
    if MARKER not in line:
        return None
    payload = line[line.index(MARKER):].strip()
    parts = payload.split("|")
    result = {"raw": payload}
    if parts:
        result["record"] = parts[0].replace(MARKER, "").strip()
    for part in parts[1:]:
        if "=" in part:
            k, v = part.split("=", 1)
            result[k.strip()] = v.strip()
    return result


def bool_event(events: list[dict], event: str, **matches: str) -> bool:
    for e in events:
        if e.get("event") != event:
            continue
        if all(e.get(k) == v for k, v in matches.items()):
            return True
    return False


def summarize_events(events: list[dict], state: dict) -> dict:
    counts = Counter(e.get("event", "") for e in events)
    role = state.get("probe", {}).get("role")
    remote_joins = [e for e in events if e.get("event") == "lifecycle.player.join" and e.get("isHostPlayer") == "false"]
    remote_left = [e for e in events if e.get("event") == "lifecycle.player.left" and e.get("isHostPlayer") == "false"]
    clientdata_set_channels = sorted({e.get("channel") for e in events if e.get("event") == "clientdata.set.ok" and e.get("channel")})
    clientdata_recv_channels = sorted({e.get("channel") for e in events if e.get("event") == "clientdata.receive.client" and e.get("channel")})
    request_replies = {
        rid: any(e.get("event") == "network.reply.client" and e.get("requestId") == rid and e.get("accepted") == "true" for e in events)
        for rid in [f"N-RPC-{i:02d}" for i in range(1, 11)]
    }
    return {
        "schema": "smml-gp0-network-storage-probe-results/1",
        "version": state.get("version"),
        "run_id": state.get("probe", {}).get("run_id"),
        "role": role,
        "collected_at_utc": utc_now(),
        "event_count": len(events),
        "event_counts": dict(counts),
        "server_create_count": counts.get("lifecycle.server.create", 0),
        "client_create_count": counts.get("lifecycle.client.create", 0),
        "remote_join_count": len(remote_joins),
        "remote_left_count": len(remote_left),
        "remote_server_envelope_seen": any(e.get("event") == "network.envelope.server" and e.get("senderIsHost") == "false" for e in events),
        "client_reply_seen": counts.get("network.reply.client", 0) > 0,
        "client_broadcast_seen": counts.get("network.broadcast.client", 0) > 0,
        "clientdata_set_channels": clientdata_set_channels,
        "clientdata_receive_channels": clientdata_recv_channels,
        "clientdata_initial_receive": any(e.get("event") == "clientdata.receive.client" and e.get("reason") == "initial-server-state" for e in events),
        "request_replies_accepted": request_replies,
        "unknown_contract_rejected": bool_event(events, "network.envelope.reject", requestId="N-RPC-06", reason="unknown-contract"),
        "bad_version_rejected": bool_event(events, "network.envelope.reject", requestId="N-RPC-07", reason="unknown-contract"),
        "invalid_payload_rejected": bool_event(events, "network.handler.reject", requestId="N-RPC-08"),
        "handler_throw_seen": bool_event(events, "network.handler.error", requestId="N-RPC-09"),
        "post_throw_success": bool_event(events, "network.handler.ok", requestId="N-RPC-10"),
        "nil_envelope_rejected": bool_event(events, "network.envelope.reject", reason="envelope-not-table"),
        "storage_absent_seen": counts.get("storage.load.absent", 0) > 0,
        "storage_schema1_saved": counts.get("storage.save.schema1", 0) > 0,
        "storage_schema1_loaded": counts.get("storage.load.schema1", 0) > 0,
        "storage_schema2_saved": counts.get("storage.save.schema2", 0) > 0,
        "storage_schema2_loaded": counts.get("storage.load.schema2", 0) > 0,
        "storage_namespace_checks_ok": all(e.get("success") == "true" for e in events if e.get("event") == "storage.namespace.check") and any(e.get("event") == "storage.namespace.check" for e in events),
    }


def collect_data(state_dir: Path, output: Path) -> dict:
    state = load_state(state_dir)
    root = Path(state["game_root"]).resolve()
    logs_dir = root / "Logs"
    since = float(state.get("probe", {}).get("armed_epoch") or state.get("installed_epoch", 0))
    run_id = state.get("probe", {}).get("run_id")

    candidates: list[Path] = []
    if logs_dir.is_dir():
        for p in sorted(logs_dir.glob("game-*.log")):
            try:
                if p.stat().st_mtime >= since - 60:
                    candidates.append(p)
            except OSError:
                pass

    events: list[dict] = []
    diagnostics: list[dict] = []
    for p in candidates:
        text = p.read_text("utf-8", errors="replace")
        for line_no, line in enumerate(text.splitlines(), 1):
            parsed = parse_event_line(line)
            if parsed and (run_id is None or parsed.get("runId") == run_id):
                parsed["source_log"] = p.name
                parsed["line"] = line_no
                events.append(parsed)
            if any(x in line for x in ("[Lua] ERROR:", "Failed to load file:", "Load failed", "SMMLProbeNS", MARKER)):
                diagnostics.append({"source_log": p.name, "line": line_no, "text": line})

    summary = summarize_events(events, state)
    summary["candidate_logs"] = [p.name for p in candidates]

    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        zf.writestr("summary.json", json.dumps(summary, indent=2, sort_keys=True))
        zf.writestr("state.json", json.dumps(state, indent=2, sort_keys=True))
        zf.writestr("events.json", json.dumps(events, indent=2, sort_keys=True))
        zf.writestr("probe-lines.txt", "\n".join(e["raw"] for e in events) + ("\n" if events else ""))
        zf.writestr("diagnostic-lines.txt", "\n".join(f"{d['source_log']}:{d['line']}: {d['text']}" for d in diagnostics) + ("\n" if diagnostics else ""))

        if events:
            keys = sorted({k for e in events for k in e.keys() if k != "raw"})
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=keys, extrasaction="ignore")
            w.writeheader()
            for e in events:
                w.writerow({k: e.get(k, "") for k in keys})
            zf.writestr("events.csv", buf.getvalue())

        snap = state.get("probe", {}).get("snapshot")
        if snap:
            zf.writestr("snapshot-manifest.json", json.dumps(snap.get("manifest", {}), indent=2, sort_keys=True))

        for p in candidates:
            zf.write(p, f"raw-logs/{p.name}")

    return summary


def collect(args: argparse.Namespace) -> None:
    state_dir = args.state_dir.expanduser().resolve()
    output = args.output.expanduser().resolve() if args.output else Path.cwd() / f"smml-gp0-ns-results-{datetime.now().strftime('%Y%m%d-%H%M%S')}.zip"
    summary = collect_data(state_dir, output)
    print(f"[OK] Collected {summary['event_count']} events for role={summary['role']} run={summary['run_id']}")
    print(output)


def disable_config(state_dir: Path, state: dict, reason: str) -> None:
    root = Path(state["game_root"]).resolve()
    data = render_config(False, "disabled", "DISARMED")
    atomic_write(root / CONFIG_PATH, data)
    state["config"] = {
        "path": CONFIG_PATH,
        "sha256": sha256_bytes(data),
        "enabled": False,
        "role": "disabled",
        "run_id": "DISARMED",
    }
    state.setdefault("probe", {})["armed"] = False
    state["probe"]["disarmed_at_utc"] = utc_now()
    invalidate_cache(root, state_dir, state, reason)


def disarm(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("Probe is not installed.")
    disable_config(state_dir, state, "disarm")
    save_state(state_dir, state)
    print("[OK] Probe disarmed. Host Save changes were kept; use restore-save or finish-host semantics via finish.")


def restore_save_internal(state_dir: Path, state: dict) -> None:
    probe_state = state.get("probe", {})
    if probe_state.get("role") != "host":
        raise SystemExit("This state is not the host role; no Save snapshot is expected.")
    snap = probe_state.get("snapshot")
    if not snap:
        raise SystemExit("No Save snapshot is recorded in host state.")
    if snap.get("restored"):
        return

    snapshot_dir = Path(snap["dir"]).resolve()
    manifest = snap["manifest"]
    problems = verify_snapshot(snapshot_dir, manifest)
    if problems:
        raise SystemExit("Snapshot integrity failure:\n" + "\n".join(problems[:20]))

    save_root = Path(probe_state["save_root"]).resolve()
    assert_disjoint(save_root, state_dir, "save_root", "state_dir")
    quarantine = state_dir / "quarantine" / f"Save.post-probe-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    quarantine.parent.mkdir(parents=True, exist_ok=True)
    if save_root.exists():
        shutil.move(str(save_root), str(quarantine))
    shutil.copytree(snapshot_dir, save_root, symlinks=False)

    restore_problems = verify_snapshot(save_root, manifest)
    if restore_problems:
        raise SystemExit("Restored Save verification failed:\n" + "\n".join(restore_problems[:20]))

    snap["restored"] = True
    snap["restored_at_utc"] = utc_now()
    snap["post_probe_quarantine"] = str(quarantine)
    disable_config(state_dir, state, "restore-save")


def restore_save(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    restore_save_internal(state_dir, state)
    save_state(state_dir, state)
    print("[OK] Host Save snapshot restored and verified. Post-probe Save was quarantined.")


def uninstall_internal(state_dir: Path, state: dict) -> None:
    root = Path(state["game_root"]).resolve()
    if state.get("probe", {}).get("armed"):
        raise SystemExit("Uninstall refused while probe is armed. Run finish, restore-save (host), or disarm first.")

    problems = verify_installed_files(state)
    if problems:
        raise SystemExit("Uninstall refused because owned files drifted:\n" + "\n".join(problems))

    for rel, rec in state.get("files", {}).items():
        backup = Path(rec["backup"]).resolve()
        data = backup.read_bytes()
        if sha256_bytes(data) != rec["before_sha256"]:
            raise SystemExit(f"Backup integrity failure: {backup}")
        atomic_write(root / rel, data)

    for rel in list(state.get("runtime_files", {})) + [CONFIG_PATH]:
        p = root / rel
        if p.exists():
            p.unlink()
    try:
        (root / PROBE_DIR).rmdir()
    except OSError:
        pass

    cache = root / CACHE_PATH
    if cache.exists():
        quarantine = state_dir / "quarantine" / f"core_data.cbo.post-probe-{datetime.now().strftime('%Y%m%d-%H%M%S-%f')}"
        quarantine.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(cache), str(quarantine))
        state["cache"].setdefault("quarantined", []).append(str(quarantine))

    if state.get("cache", {}).get("existed"):
        backup = Path(state["cache"]["backup"]).resolve()
        expected = state["cache"]["before_sha256"]
        if not backup.is_file() or sha256_file(backup) != expected:
            raise SystemExit(f"Cache backup integrity failure: {backup}")
        atomic_write(cache, backup.read_bytes())

    failures = []
    if sha256_file(root / TARGET) != TARGET_SHA256:
        failures.append(TARGET)
    if state.get("cache", {}).get("existed"):
        if not cache.is_file() or sha256_file(cache) != state["cache"]["before_sha256"]:
            failures.append(CACHE_PATH)
    elif cache.exists():
        failures.append(CACHE_PATH + " (should remain absent)")
    if failures:
        raise SystemExit("Restoration verification failed: " + ", ".join(failures))

    state["installed"] = False
    state["phase"] = "uninstalled"
    state["uninstalled_at_utc"] = utc_now()


def uninstall(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    if not state.get("installed"):
        raise SystemExit("State says the probe is not installed.")
    uninstall_internal(state_dir, state)
    save_state(state_dir, state)
    print("[OK] Probe removed; vanilla SurvivalGame.lua and original cache state restored.")


def finish(args: argparse.Namespace) -> None:
    require_game_stopped()
    state_dir = args.state_dir.expanduser().resolve()
    state = load_state(state_dir)
    output = args.output.expanduser().resolve() if args.output else Path.cwd() / f"smml-gp0-ns-{state.get('probe', {}).get('role')}-results-{datetime.now().strftime('%Y%m%d-%H%M%S')}.zip"
    summary = collect_data(state_dir, output)

    if state.get("probe", {}).get("role") == "host":
        restore_save_internal(state_dir, state)
    else:
        disable_config(state_dir, state, "finish-client")

    uninstall_internal(state_dir, state)
    state["finish"] = {"at_utc": utc_now(), "results": str(output), "summary": summary}
    save_state(state_dir, state)
    print(f"[OK] Results collected: {output}")
    if summary.get("role") == "host":
        print("[OK] Host Save snapshot restored and probe removed.")
    else:
        print("[OK] Client probe removed.")


def load_result_zip(path: Path) -> tuple[dict, list[dict]]:
    with zipfile.ZipFile(path, "r") as zf:
        summary = json.loads(zf.read("summary.json").decode("utf-8"))
        events = json.loads(zf.read("events.json").decode("utf-8"))
    return summary, events


def distinct_source_logs(events: list[dict], event_names: set[str]) -> set[str]:
    return {e.get("source_log", "") for e in events if e.get("event") in event_names and e.get("source_log")}


def merge_results(args: argparse.Namespace) -> None:
    host_path = args.host.expanduser().resolve()
    client_path = args.client.expanduser().resolve()
    host_summary, host_events = load_result_zip(host_path)
    client_summary, client_events = load_result_zip(client_path)

    if host_summary.get("role") != "host":
        raise SystemExit(f"Host result ZIP has role={host_summary.get('role')!r}, expected 'host'")
    if client_summary.get("role") != "client":
        raise SystemExit(f"Client result ZIP has role={client_summary.get('role')!r}, expected 'client'")
    if host_summary.get("run_id") != client_summary.get("run_id"):
        raise SystemExit(f"Run ID mismatch: host={host_summary.get('run_id')} client={client_summary.get('run_id')}")

    common_clientdata_channels = sorted(set(host_summary.get("clientdata_set_channels", [])) & set(client_summary.get("clientdata_receive_channels", [])))
    storage_session_logs = distinct_source_logs(host_events, {"storage.save.schema1", "storage.load.schema1", "storage.load.schema2"})

    checks = {
        "remote_client_to_server": host_summary.get("remote_server_envelope_seen") is True,
        "server_to_remote_client": any(e.get("event") == "network.reply.client" and e.get("requestId") == "N-RPC-01" and e.get("accepted") == "true" for e in client_events),
        "server_broadcast_to_remote_client": client_summary.get("client_broadcast_seen") is True,
        "unknown_contract_rejected": host_summary.get("unknown_contract_rejected") is True,
        "bad_version_rejected": host_summary.get("bad_version_rejected") is True,
        "invalid_payload_rejected": host_summary.get("invalid_payload_rejected") is True,
        "handler_error_isolated": host_summary.get("handler_throw_seen") is True and host_summary.get("post_throw_success") is True and client_summary.get("request_replies_accepted", {}).get("N-RPC-10") is True,
        "nil_envelope_fail_open": host_summary.get("nil_envelope_rejected") is True or any(e.get("event") == "network.send.client.error" and e.get("requestId") == "N-RPC-11" for e in client_events),
        "setClientData_usable_channel": len(common_clientdata_channels) >= 1,
        "setClientData_new_client_initial_state": client_summary.get("clientdata_initial_receive") is True,
        "remote_disconnect_reconnect": host_summary.get("remote_join_count", 0) >= 2 and host_summary.get("remote_left_count", 0) >= 1,
        "world_or_process_reload": host_summary.get("server_create_count", 0) >= 3,
        "storage_absent_to_schema1": host_summary.get("storage_absent_seen") is True and host_summary.get("storage_schema1_saved") is True,
        "storage_schema1_reload_and_migration": host_summary.get("storage_schema1_loaded") is True and host_summary.get("storage_schema2_saved") is True,
        "storage_schema2_survives_restart": host_summary.get("storage_schema2_loaded") is True and len(storage_session_logs) >= 3,
        "logical_namespace_isolation": host_summary.get("storage_namespace_checks_ok") is True,
    }
    required = list(checks)
    overall = all(checks[k] for k in required)

    combined = {
        "schema": "smml-gp0-network-storage-probe-combined/1",
        "version": VERSION,
        "run_id": host_summary.get("run_id"),
        "merged_at_utc": utc_now(),
        "host_result": str(host_path),
        "client_result": str(client_path),
        "host_summary": host_summary,
        "client_summary": client_summary,
        "common_clientdata_channels": common_clientdata_channels,
        "storage_session_logs": sorted(storage_session_logs),
        "checks": checks,
        "overall_pass": overall,
    }

    output = args.output.expanduser().resolve() if args.output else Path.cwd() / f"smml-gp0-ns-combined-{host_summary.get('run_id')}.zip"
    output.parent.mkdir(parents=True, exist_ok=True)
    combined_events = []
    for e in host_events:
        x = dict(e)
        x["result_side"] = "host"
        combined_events.append(x)
    for e in client_events:
        x = dict(e)
        x["result_side"] = "client"
        combined_events.append(x)

    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as zf:
        zf.writestr("combined-summary.json", json.dumps(combined, indent=2, sort_keys=True))
        zf.writestr("combined-events.json", json.dumps(combined_events, indent=2, sort_keys=True))
        if combined_events:
            keys = sorted({k for e in combined_events for k in e.keys() if k != "raw"})
            buf = io.StringIO()
            w = csv.DictWriter(buf, fieldnames=keys, extrasaction="ignore")
            w.writeheader()
            for e in combined_events:
                w.writerow({k: e.get(k, "") for k in keys})
            zf.writestr("combined-events.csv", buf.getvalue())
        lines = [f"GP0.5 combined run: {combined['run_id']}", f"overall_pass={str(overall).lower()}", ""]
        for key, value in checks.items():
            lines.append(f"{'PASS' if value else 'FAIL'} {key}")
        lines.append("")
        lines.append("usable setClientData channels: " + (", ".join(common_clientdata_channels) if common_clientdata_channels else "none"))
        zf.writestr("SUMMARY.txt", "\n".join(lines) + "\n")

    print(f"[{'PASS' if overall else 'PARTIAL'}] GP0.5 combined analysis: {host_summary.get('run_id')}")
    for key, value in checks.items():
        print(f"{'PASS' if value else 'FAIL':4} {key}")
    print(f"Usable setClientData channels: {', '.join(common_clientdata_channels) if common_clientdata_channels else 'none'}")
    print(output)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="SMML GP0.5 Network / Storage Probe")
    p.add_argument("--state-dir", type=Path, default=default_state_dir(), help="Persistent per-installation probe state directory")
    sub = p.add_subparsers(dest="command", required=True)

    i = sub.add_parser("install", help="Install passive SurvivalGame hook/runtime; probe remains disabled")
    i.add_argument("game_root", type=Path)
    i.set_defaults(func=install)

    ah = sub.add_parser("arm-host", help="Snapshot host Save and enable host/server probe role")
    ah.add_argument("--save-root", type=Path, required=True, help="Exact host Scrap Mechanic User_*/Save directory")
    ah.add_argument("--run-id", help="Shared run ID; generated if omitted")
    ah.set_defaults(func=arm_host)

    ac = sub.add_parser("arm-client", help="Enable remote-client probe role; no Save snapshot")
    ac.add_argument("--run-id", required=True, help="Exactly the run ID used by arm-host")
    ac.set_defaults(func=arm_client)

    s = sub.add_parser("status", help="Show installed/armed role, hashes, cache and snapshot state")
    s.set_defaults(func=status)

    c = sub.add_parser("collect", help="Collect current role logs without restoring/uninstalling")
    c.add_argument("--output", type=Path)
    c.set_defaults(func=collect)

    d = sub.add_parser("disarm", help="Disable probe but keep current host Save changes")
    d.set_defaults(func=disarm)

    r = sub.add_parser("restore-save", help="Host only: restore and verify pre-probe Save snapshot")
    r.set_defaults(func=restore_save)

    u = sub.add_parser("uninstall", help="Restore vanilla SurvivalGame.lua and original cache state")
    u.set_defaults(func=uninstall)

    f = sub.add_parser("finish", help="Collect results, restore host Save if needed, then uninstall")
    f.add_argument("--output", type=Path)
    f.set_defaults(func=finish)

    m = sub.add_parser("merge-results", help="Cross-correlate host/client result ZIPs and score GP0.5 evidence")
    m.add_argument("--host", type=Path, required=True)
    m.add_argument("--client", type=Path, required=True)
    m.add_argument("--output", type=Path)
    m.set_defaults(func=merge_results)

    return p


def main() -> int:
    args = build_parser().parse_args()
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
